name: CI

on: [push]

jobs:
  ubuntu:
    runs-on: dotfiles
    container: ubuntu:latest
    strategy:
      matrix:
        install_script: ['WSL/.bin/install.sh', 'shared/.bin/install.sh']
    steps:
      - uses: actions/checkout@v5
      - name: Install required packages
        run: apt-get update && apt-get install -y git sudo
      - name: Install dotfiles
        run: ${{ matrix.install_script }} install

  alpine:
    runs-on: dotfiles
    container: alpine:latest
    strategy:
      matrix:
        install_script: ['WSL/.bin/install.sh', 'shared/.bin/install.sh']
    steps:
      - uses: actions/checkout@v5
      - name: Install required packages
        run: apk add git sudo bash
      - name: Install dotfiles
        run: ${{ matrix.install_script }} install

  arch:
    runs-on: dotfiles
    container: archlinux:base
    strategy:
      matrix:
        install_script: ['WSL/.bin/install.sh', 'shared/.bin/install.sh']
    steps:
      - uses: actions/checkout@v5
      - name: Update packages
        run: pacman -Syu --noconfirm
      - name: Install required packages
        run: pacman -S --noconfirm git sudo
      - name: Install dotfiles
        run: ${{ matrix.install_script }} install

  lint:
    runs-on: dotfiles
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v5
      - name: Update packages
        run: apt-get update
      - name: Install required packages
        run: apt-get update; apt-get install -y shellcheck
      - name: Execute shellcheck
        run: test $(shellcheck  -f gcc ~/.zshrc ~/.zsh/rc/* | grep -v "SC1036\|SC1056\|SC1070\|SC1072\|SC1073\|SC1083\|SC2034\|SC2139\|SC2148\|SC1090\|SC1117\|SC2206\|SC1009\|SC2016\|SC2046\|SC2154" | tee -a /dev/stderr | wc -l) -le 1
